import { categoryIds, type ProductCategoryId } from "@/content/categories";
import { createTodoContent, createTodoSeo } from "@/content/products/shared";
import type { ServiceProduct } from "@/types/product";

export const privateServices = [
  {
    id: "private-tours",
    slug: "private-tours",
    type: "service",
    category: categoryIds.privateServices,
    status: "draft",
    priority: "supporting",
    heroImage: "",
    heroAlt: "TODO: Add Private Tours hero image alt text.",
    gallery: [],
    relatedProductIds: [],
    recommendedServiceIds: [],
    recommendedExperienceIds: [],
    tripBuilderEligible: true,
    seo: createTodoSeo("Private Tours"),
    content: createTodoContent("Private Tours"),
  },
  {
    id: "yacht-rentals",
    slug: "yacht-rentals",
    type: "service",
    category: categoryIds.privateServices,
    status: "draft",
    priority: "supporting",
    heroImage: "",
    heroAlt: "TODO: Add Yacht Rentals hero image alt text.",
    gallery: [],
    relatedProductIds: [],
    recommendedServiceIds: [],
    recommendedExperienceIds: ["isla-mujeres"],
    tripBuilderEligible: true,
    seo: createTodoSeo("Yacht Rentals"),
    content: createTodoContent("Yacht Rentals"),
  },
  {
    id: "fishing-tours",
    slug: "fishing-tours",
    type: "service",
    category: categoryIds.privateServices,
    status: "draft",
    priority: "supporting",
    heroImage: "",
    heroAlt: "TODO: Add Fishing Tours hero image alt text.",
    gallery: [],
    relatedProductIds: [],
    recommendedServiceIds: [],
    recommendedExperienceIds: [],
    tripBuilderEligible: true,
    seo: createTodoSeo("Fishing Tours"),
    content: createTodoContent("Fishing Tours"),
  },
  {
    id: "romantic-experiences",
    slug: "romantic-experiences",
    type: "service",
    category: categoryIds.privateServices,
    status: "draft",
    priority: "supporting",
    heroImage: "",
    heroAlt: "TODO: Add Romantic Experiences hero image alt text.",
    gallery: [],
    relatedProductIds: [],
    recommendedServiceIds: [],
    recommendedExperienceIds: ["isla-mujeres", "tulum"],
    tripBuilderEligible: true,
    seo: createTodoSeo("Romantic Experiences"),
    content: createTodoContent("Romantic Experiences"),
  },
  {
    id: "concierge-services",
    slug: "concierge-services",
    type: "service",
    category: categoryIds.privateServices,
    status: "draft",
    priority: "supporting",
    heroImage: "",
    heroAlt: "TODO: Add Concierge Services hero image alt text.",
    gallery: [],
    relatedProductIds: [],
    recommendedServiceIds: [],
    recommendedExperienceIds: [],
    tripBuilderEligible: true,
    seo: createTodoSeo("Concierge Services"),
    content: createTodoContent("Concierge Services"),
  },
] as const satisfies Array<ServiceProduct & { category: ProductCategoryId }>;
