import { categoryIds, type ProductCategoryId } from "@/content/categories";
import { createTodoContent, createTodoSeo } from "@/content/products/shared";
import type { ServiceProduct } from "@/types/product";

export const transportationRentalServices = [
  {
    id: "airport-transportation",
    slug: "airport-transportation",
    type: "service",
    category: categoryIds.transportationRentals,
    status: "draft",
    priority: "supporting",
    heroImage: "",
    heroAlt: "TODO: Add Airport Transportation hero image alt text.",
    gallery: [],
    relatedProductIds: [],
    recommendedServiceIds: [],
    recommendedExperienceIds: [],
    tripBuilderEligible: true,
    seo: createTodoSeo("Airport Transportation"),
    content: createTodoContent("Airport Transportation"),
  },
  {
    id: "private-transportation",
    slug: "private-transportation",
    type: "service",
    category: categoryIds.transportationRentals,
    status: "draft",
    priority: "supporting",
    heroImage: "",
    heroAlt: "TODO: Add Private Transportation hero image alt text.",
    gallery: [],
    relatedProductIds: [],
    recommendedServiceIds: [],
    recommendedExperienceIds: [],
    tripBuilderEligible: true,
    seo: createTodoSeo("Private Transportation"),
    content: createTodoContent("Private Transportation"),
  },
  {
    id: "car-rentals",
    slug: "car-rentals",
    type: "service",
    category: categoryIds.transportationRentals,
    status: "draft",
    priority: "supporting",
    heroImage: "",
    heroAlt: "TODO: Add Car Rentals hero image alt text.",
    gallery: [],
    relatedProductIds: [],
    recommendedServiceIds: [],
    recommendedExperienceIds: [],
    tripBuilderEligible: true,
    seo: createTodoSeo("Car Rentals"),
    content: createTodoContent("Car Rentals"),
  },
] as const satisfies Array<ServiceProduct & { category: ProductCategoryId }>;
