import { categoryIds, type ProductCategoryId } from "@/content/categories";
import { createTodoContent, createTodoSeo } from "@/content/products/shared";
import type { ExperienceProduct } from "@/types/product";

export const adventureExperiences = [
  {
    id: "sian-kaan",
    slug: "sian-kaan",
    type: "experience",
    category: categoryIds.adventure,
    status: "draft",
    priority: "standard",
    heroImage: "",
    heroAlt: "TODO: Add Sian Ka'an hero image alt text.",
    gallery: [],
    relatedProductIds: [],
    recommendedServiceIds: [],
    recommendedExperienceIds: [],
    tripBuilderEligible: true,
    seo: createTodoSeo("Sian Ka'an"),
    content: createTodoContent("Sian Ka'an"),
  },
  {
    id: "atv-adventure",
    slug: "atv-adventure",
    type: "experience",
    category: categoryIds.adventure,
    status: "draft",
    priority: "standard",
    heroImage: "",
    heroAlt: "TODO: Add ATV Adventure hero image alt text.",
    gallery: [],
    relatedProductIds: ["cenotes"],
    recommendedServiceIds: ["private-transportation"],
    recommendedExperienceIds: ["cenotes"],
    tripBuilderEligible: true,
    seo: createTodoSeo("ATV Adventure"),
    content: createTodoContent("ATV Adventure"),
  },
  {
    id: "atv-snorkeling-express",
    slug: "atv-snorkeling-express",
    type: "experience",
    category: categoryIds.adventure,
    status: "draft",
    priority: "standard",
    heroImage: "",
    heroAlt: "TODO: Add ATV + Snorkeling Express hero image alt text.",
    gallery: [],
    relatedProductIds: ["atv-adventure", "snorkeling-with-turtles-cenote"],
    recommendedServiceIds: [],
    recommendedExperienceIds: ["atv-adventure", "snorkeling-with-turtles-cenote"],
    tripBuilderEligible: true,
    seo: createTodoSeo("ATV + Snorkeling Express"),
    content: createTodoContent("ATV + Snorkeling Express"),
  },
  {
    id: "monkey-sanctuary",
    slug: "monkey-sanctuary",
    type: "experience",
    category: categoryIds.adventure,
    status: "draft",
    priority: "standard",
    heroImage: "",
    heroAlt: "TODO: Add Monkey Sanctuary hero image alt text.",
    gallery: [],
    relatedProductIds: [],
    recommendedServiceIds: [],
    recommendedExperienceIds: [],
    tripBuilderEligible: true,
    seo: createTodoSeo("Monkey Sanctuary"),
    content: createTodoContent("Monkey Sanctuary"),
  },
] as const satisfies Array<ExperienceProduct & { category: ProductCategoryId }>;
