import { categoryIds, type ProductCategoryId } from "@/content/categories";
import { createTodoContent, createTodoSeo } from "@/content/products/shared";
import type { ExperienceProduct } from "@/types/product";

export const caribbeanIslandExperiences = [
  {
    id: "isla-mujeres",
    slug: "isla-mujeres",
    legacyPath: "/isla-mujeres",
    type: "experience",
    category: categoryIds.caribbeanIslands,
    status: "published",
    priority: "featured",
    assetBasePath: "/images/experiences/isla-mujeres",
    cardImage: "/images/experiences/isla-mujeres/card.jpg",
    cardImageAlt: "Isla Mujeres turquoise water tour experience.",
    cardImageObjectPosition: "center 56%",
    heroImage: "/tours/isla-mujeres.png",
    heroAlt: "Isla Mujeres",
    gallery: [
      "/tours/isla-mujeres-gallery/1.jpg",
      "/tours/isla-mujeres-gallery/2.jpg",
      "/tours/isla-mujeres-gallery/3.jpg",
      "/tours/isla-mujeres-gallery/4.jpg",
      "/tours/isla-mujeres-gallery/5.jpg",
      "/tours/isla-mujeres-gallery/6.jpg",
      "/tours/isla-mujeres-gallery/7.jpg",
      "/tours/isla-mujeres-gallery/8.jpg",
    ],
    relatedProductIds: [],
    recommendedServiceIds: [],
    recommendedExperienceIds: [],
    tripBuilderEligible: true,
    seo: {
      title: "Isla Mujeres Tours | Mayan Xperience Tours",
      description:
        "Discover Isla Mujeres tours from the Riviera Maya with turquoise waters, Playa Norte, snorkeling, catamaran experiences and private options.",
      openGraph: {
        title: "Isla Mujeres Tours | Mayan Xperience Tours",
        description:
          "Discover Isla Mujeres tours from the Riviera Maya with turquoise waters, Playa Norte, snorkeling, catamaran experiences and private options.",
        url: "/isla-mujeres",
        images: [
          {
            url: "/tours/isla-mujeres.png",
            width: 1200,
            height: 630,
            alt: "Isla Mujeres turquoise water tour experience",
          },
        ],
      },
      twitter: {
        card: "summary_large_image",
        title: "Isla Mujeres Tours | Mayan Xperience Tours",
        description:
          "Discover Isla Mujeres tours from the Riviera Maya with turquoise waters, Playa Norte, snorkeling, catamaran experiences and private options.",
        images: [
          {
            url: "/tours/isla-mujeres.png",
            alt: "Isla Mujeres turquoise water tour experience",
          },
        ],
      },
    },
    content: {
      en: {
        title: "Isla Mujeres",
        subtitle:
          "Discover Playa Norte, internationally recognized as one of the world's most beautiful beaches. Enjoy turquoise waters, soft white sand and the unique charm of Isla Mujeres in an experience tailored to your travel style.",
        galleryTitle: "Experience Gallery",
        whatToExpectTitle: "What to Expect",
        whatToExpect:
          "Escape to the Caribbean paradise of Isla Mujeres, a destination famous for its crystal-clear waters, relaxed atmosphere and breathtaking scenery. Depending on the experience you choose, you may enjoy sailing across the Caribbean Sea, snorkeling in vibrant reefs, relaxing at exclusive beach clubs or exploring the island at your own pace.\n\nEvery visit offers a unique combination of natural beauty, local culture and unforgettable moments designed to create lasting memories.",
        experienceStylesTitle: "Available Experience Styles",
        experienceStyles: [
          "Luxury Catamaran Experience",
          "Small Group Sailing Adventure",
          "Family-Friendly Island Escape",
          "Beach Club & Relaxation Day",
          "Private Customized Experience",
        ],
        perfectForTitle: "Perfect For",
        perfectFor: [
          "❤️ Couples",
          "👨‍👩‍👧‍👦 Families",
          "🎉 Groups of Friends",
          "✨ Honeymooners",
          "🏖️ First-Time Visitors",
        ],
        recommendationTitle: "Why We Recommend This Experience",
        recommendation:
          "Isla Mujeres is one of the most requested experiences in the Riviera Maya thanks to its combination of turquoise waters, relaxed island atmosphere and flexible options for every type of traveler.",
        whatsappButton: "Get Personalized Quote",
        whatsappMessage:
          "Hello Mayan Xperience Tours! I am interested in the Isla Mujeres Experience.",
      },
      es: {
        title: "Isla Mujeres",
        subtitle:
          "Descubre Playa Norte, reconocida internacionalmente como una de las playas más hermosas del mundo. Disfruta aguas turquesa, arena blanca y suave, y el encanto único de Isla Mujeres en una experiencia adaptada a tu estilo de viaje.",
        galleryTitle: "Galería de la Experiencia",
        whatToExpectTitle: "Qué Puedes Esperar",
        whatToExpect:
          "Escápate al paraíso caribeño de Isla Mujeres, un destino famoso por sus aguas cristalinas, ambiente relajado y paisajes impresionantes. Según la experiencia que elijas, podrás navegar por el mar Caribe, hacer snorkel en arrecifes llenos de vida, relajarte en exclusivos clubes de playa o explorar la isla a tu propio ritmo.\n\nCada visita ofrece una combinación única de belleza natural, cultura local y momentos inolvidables diseñados para crear recuerdos duraderos.",
        experienceStylesTitle: "Estilos de Experiencia Disponibles",
        experienceStyles: [
          "Experiencia de Catamarán de Lujo",
          "Aventura de Navegación en Grupo Pequeño",
          "Escapada Familiar a la Isla",
          "Día de Playa Club y Relajación",
          "Experiencia Privada Personalizada",
        ],
        perfectForTitle: "Ideal Para",
        perfectFor: [
          "❤️ Parejas",
          "👨‍👩‍👧‍👦 Familias",
          "🎉 Grupos de Amigos",
          "✨ Luna de Miel",
          "🏖️ Visitantes por Primera Vez",
        ],
        recommendationTitle: "Por Qué Recomendamos Esta Experiencia",
        recommendation:
          "Isla Mujeres es una de las experiencias más solicitadas en la Riviera Maya gracias a su combinación de aguas turquesa, ambiente relajado de isla y opciones flexibles para cada tipo de viajero.",
        whatsappButton: "Solicitar Cotización Personalizada",
        whatsappMessage:
          "Hola Mayan Xperience Tours! Estoy interesado en la Experiencia Isla Mujeres.",
      },
      fr: {
        title: "Isla Mujeres",
        subtitle:
          "Découvrez Playa Norte, reconnue internationalement comme l'une des plus belles plages du monde. Profitez des eaux turquoise, du sable blanc et doux, et du charme unique d'Isla Mujeres dans une expérience adaptée à votre style de voyage.",
        galleryTitle: "Galerie de l'Expérience",
        whatToExpectTitle: "À Quoi Vous Attendre",
        whatToExpect:
          "Évadez-vous vers le paradis caribéen d'Isla Mujeres, une destination réputée pour ses eaux cristallines, son atmosphère détendue et ses paysages à couper le souffle. Selon l'expérience choisie, vous pourrez naviguer sur la mer des Caraïbes, faire du snorkeling dans des récifs colorés, vous détendre dans des clubs de plage exclusifs ou explorer l'île à votre rythme.\n\nChaque visite offre une combinaison unique de beauté naturelle, de culture locale et de moments inoubliables pensés pour créer des souvenirs durables.",
        experienceStylesTitle: "Styles d'Expérience Disponibles",
        experienceStyles: [
          "Expérience en Catamaran de Luxe",
          "Aventure en Voilier en Petit Groupe",
          "Escapade Familiale sur l'Île",
          "Journée Beach Club et Détente",
          "Expérience Privée Personnalisée",
        ],
        perfectForTitle: "Parfait Pour",
        perfectFor: [
          "❤️ Couples",
          "👨‍👩‍👧‍👦 Familles",
          "🎉 Groupes d'Amis",
          "✨ Voyages de Noces",
          "🏖️ Premiers Visiteurs",
        ],
        recommendationTitle: "Pourquoi Nous Recommandons Cette Expérience",
        recommendation:
          "Isla Mujeres est l'une des expériences les plus demandées dans la Riviera Maya grâce à sa combinaison d'eaux turquoise, d'ambiance insulaire détendue et d'options flexibles pour chaque type de voyageur.",
        whatsappButton: "Obtenir un Devis Personnalisé",
        whatsappMessage:
          "Bonjour Mayan Xperience Tours! Je suis intéressé par l'Expérience Isla Mujeres.",
      },
    },
  },
  {
    id: "cozumel",
    slug: "cozumel",
    type: "experience",
    category: categoryIds.caribbeanIslands,
    status: "draft",
    priority: "standard",
    assetBasePath: "/images/experiences/cozumel",
    cardImage: "/images/experiences/cozumel/card.jpg",
    cardImageAlt:
      "Snorkeler swimming above starfish in the turquoise waters of Cozumel.",
    cardImageObjectPosition: "center 58%",
    heroImage: "",
    heroAlt: "TODO: Add Cozumel hero image alt text.",
    gallery: [],
    relatedProductIds: [],
    recommendedServiceIds: [],
    recommendedExperienceIds: [],
    tripBuilderEligible: true,
    seo: createTodoSeo("Cozumel"),
    content: createTodoContent("Cozumel"),
  },
  {
    id: "isla-contoy",
    slug: "isla-contoy",
    type: "experience",
    category: categoryIds.caribbeanIslands,
    status: "draft",
    priority: "standard",
    heroImage: "",
    heroAlt: "TODO: Add Isla Contoy hero image alt text.",
    gallery: [],
    relatedProductIds: [],
    recommendedServiceIds: [],
    recommendedExperienceIds: ["isla-mujeres"],
    tripBuilderEligible: true,
    seo: createTodoSeo("Isla Contoy"),
    content: createTodoContent("Isla Contoy"),
  },
  {
    id: "holbox",
    slug: "holbox",
    type: "experience",
    category: categoryIds.caribbeanIslands,
    status: "draft",
    priority: "standard",
    heroImage: "",
    heroAlt: "TODO: Add Holbox hero image alt text.",
    gallery: [],
    relatedProductIds: [],
    recommendedServiceIds: [],
    recommendedExperienceIds: [],
    tripBuilderEligible: true,
    seo: createTodoSeo("Holbox"),
    content: createTodoContent("Holbox"),
  },
  {
    id: "sunset-catamaran",
    slug: "sunset-catamaran",
    type: "experience",
    category: categoryIds.caribbeanIslands,
    status: "draft",
    priority: "standard",
    heroImage: "",
    heroAlt: "TODO: Add Sunset Catamaran hero image alt text.",
    gallery: [],
    relatedProductIds: ["isla-mujeres"],
    recommendedServiceIds: ["photography", "drone-photography"],
    recommendedExperienceIds: ["isla-mujeres"],
    tripBuilderEligible: true,
    seo: createTodoSeo("Sunset Catamaran"),
    content: createTodoContent("Sunset Catamaran"),
  },
] as const satisfies Array<ExperienceProduct & { category: ProductCategoryId }>;
