import { categoryIds, type ProductCategoryId } from "@/content/categories";
import { createTodoContent, createTodoSeo } from "@/content/products/shared";
import type { ExperienceProduct } from "@/types/product";

export const caribbeanIslandExperiences = [
  {
    id: "isla-mujeres",
    slug: "isla-mujeres",
    legacyPath: "/isla-mujeres",
    type: "experience",
    category: categoryIds.caribbeanIslands,
    status: "published",
    priority: "featured",
    assetBasePath: "/images/experiences/isla-mujeres",
    cardImage: "/images/experiences/isla-mujeres/card.jpg",
    cardImageAlt: "Isla Mujeres turquoise water tour experience.",
    cardImageObjectPosition: "center 56%",
    heroImage: "/tours/isla-mujeres.png",
    heroAlt: "Isla Mujeres",
    gallery: [
      "/tours/isla-mujeres-gallery/1.jpg",
      "/tours/isla-mujeres-gallery/2.jpg",
      "/tours/isla-mujeres-gallery/3.jpg",
      "/tours/isla-mujeres-gallery/4.jpg",
      "/tours/isla-mujeres-gallery/5.jpg",
      "/tours/isla-mujeres-gallery/6.jpg",
      "/tours/isla-mujeres-gallery/7.jpg",
      "/tours/isla-mujeres-gallery/8.jpg",
    ],
    relatedProductIds: [],
    recommendedServiceIds: [],
    recommendedExperienceIds: [],
    tripBuilderEligible: true,
    seo: {
      title: "Isla Mujeres Tours | Mayan Xperience Tours",
      description:
        "Discover Isla Mujeres tours from the Riviera Maya with turquoise waters, Playa Norte, snorkeling, catamaran experiences and private options.",
      openGraph: {
        title: "Isla Mujeres Tours | Mayan Xperience Tours",
        description:
          "Discover Isla Mujeres tours from the Riviera Maya with turquoise waters, Playa Norte, snorkeling, catamaran experiences and private options.",
        url: "/isla-mujeres",
        images: [
          {
            url: "/tours/isla-mujeres.png",
            width: 1200,
            height: 630,
            alt: "Isla Mujeres turquoise water tour experience",
          },
        ],
      },
      twitter: {
        card: "summary_large_image",
        title: "Isla Mujeres Tours | Mayan Xperience Tours",
        description:
          "Discover Isla Mujeres tours from the Riviera Maya with turquoise waters, Playa Norte, snorkeling, catamaran experiences and private options.",
        images: [
          {
            url: "/tours/isla-mujeres.png",
            alt: "Isla Mujeres turquoise water tour experience",
          },
        ],
      },
    },
    content: {
      en: {
        title: "Isla Mujeres",
        subtitle:
          "Discover Playa Norte, internationally recognized as one of the world's most beautiful beaches. Enjoy turquoise waters, soft white sand and the unique charm of Isla Mujeres in an experience tailored to your travel style.",
        galleryTitle: "Experience Gallery",
        whatToExpectTitle: "What to Expect",
        whatToExpect:
          "Escape to the Caribbean paradise of Isla Mujeres, a destination famous for its crystal-clear waters, relaxed atmosphere and breathtaking scenery. Depending on the experience you choose, you may enjoy sailing across the Caribbean Sea, snorkeling in vibrant reefs, relaxing at exclusive beach clubs or exploring the island at your own pace.\n\nEvery visit offers a unique combination of natural beauty, local culture and unforgettable moments designed to create lasting memories.",
        experienceStylesTitle: "Available Experience Styles",
        experienceStyles: [
          "Luxury Catamaran Experience",
          "Small Group Sailing Adventure",
          "Family-Friendly Island Escape",
          "Beach Club & Relaxation Day",
          "Private Customized Experience",
        ],
        perfectForTitle: "Perfect For",
        perfectFor: [
          "❤️ Couples",
          "👨‍👩‍👧‍👦 Families",
          "🎉 Groups of Friends",
          "✨ Honeymooners",
          "🏖️ First-Time Visitors",
        ],
        recommendationTitle: "Why We Recommend This Experience",
        recommendation:
          "Isla Mujeres is one of the most requested experiences in the Riviera Maya thanks to its combination of turquoise waters, relaxed island atmosphere and flexible options for every type of traveler.",
        whatsappButton: "Get Personalized Quote",
        whatsappMessage:
          "Hello Mayan Xperience Tours! I am interested in the Isla Mujeres Experience.",
      },
      es: {
        title: "Isla Mujeres",
        subtitle:
          "Descubre Playa Norte, reconocida internacionalmente como una de las playas más hermosas del mundo. Disfruta aguas turquesa, arena blanca y suave, y el encanto único de Isla Mujeres en una experiencia adaptada a tu estilo de viaje.",
        galleryTitle: "Galería de la Experiencia",
        whatToExpectTitle: "Qué Puedes Esperar",
        whatToExpect:
          "Escápate al paraíso caribeño de Isla Mujeres, un destino famoso por sus aguas cristalinas, ambiente relajado y paisajes impresionantes. Según la experiencia que elijas, podrás navegar por el mar Caribe, hacer snorkel en arrecifes llenos de vida, relajarte en exclusivos clubes de playa o explorar la isla a tu propio ritmo.\n\nCada visita ofrece una combinación única de belleza natural, cultura local y momentos inolvidables diseñados para crear recuerdos duraderos.",
        experienceStylesTitle: "Estilos de Experiencia Disponibles",
        experienceStyles: [
          "Experiencia de Catamarán de Lujo",
          "Aventura de Navegación en Grupo Pequeño",
          "Escapada Familiar a la Isla",
          "Día de Playa Club y Relajación",
          "Experiencia Privada Personalizada",
        ],
        perfectForTitle: "Ideal Para",
        perfectFor: [
          "❤️ Parejas",
          "👨‍👩‍👧‍👦 Familias",
          "🎉 Grupos de Amigos",
          "✨ Luna de Miel",
          "🏖️ Visitantes por Primera Vez",
        ],
        recommendationTitle: "Por Qué Recomendamos Esta Experiencia",
        recommendation:
          "Isla Mujeres es una de las experiencias más solicitadas en la Riviera Maya gracias a su combinación de aguas turquesa, ambiente relajado de isla y opciones flexibles para cada tipo de viajero.",
        whatsappButton: "Solicitar Cotización Personalizada",
        whatsappMessage:
          "Hola Mayan Xperience Tours! Estoy interesado en la Experiencia Isla Mujeres.",
      },
      fr: {
        title: "Isla Mujeres",
        subtitle:
          "Découvrez Playa Norte, reconnue internationalement comme l'une des plus belles plages du monde. Profitez des eaux turquoise, du sable blanc et doux, et du charme unique d'Isla Mujeres dans une expérience adaptée à votre style de voyage.",
        galleryTitle: "Galerie de l'Expérience",
        whatToExpectTitle: "À Quoi Vous Attendre",
        whatToExpect:
          "Évadez-vous vers le paradis caribéen d'Isla Mujeres, une destination réputée pour ses eaux cristallines, son atmosphère détendue et ses paysages à couper le souffle. Selon l'expérience choisie, vous pourrez naviguer sur la mer des Caraïbes, faire du snorkeling dans des récifs colorés, vous détendre dans des clubs de plage exclusifs ou explorer l'île à votre rythme.\n\nChaque visite offre une combinaison unique de beauté naturelle, de culture locale et de moments inoubliables pensés pour créer des souvenirs durables.",
        experienceStylesTitle: "Styles d'Expérience Disponibles",
        experienceStyles: [
          "Expérience en Catamaran de Luxe",
          "Aventure en Voilier en Petit Groupe",
          "Escapade Familiale sur l'Île",
          "Journée Beach Club et Détente",
          "Expérience Privée Personnalisée",
        ],
        perfectForTitle: "Parfait Pour",
        perfectFor: [
          "❤️ Couples",
          "👨‍👩‍👧‍👦 Familles",
          "🎉 Groupes d'Amis",
          "✨ Voyages de Noces",
          "🏖️ Premiers Visiteurs",
        ],
        recommendationTitle: "Pourquoi Nous Recommandons Cette Expérience",
        recommendation:
          "Isla Mujeres est l'une des expériences les plus demandées dans la Riviera Maya grâce à sa combinaison d'eaux turquoise, d'ambiance insulaire détendue et d'options flexibles pour chaque type de voyageur.",
        whatsappButton: "Obtenir un Devis Personnalisé",
        whatsappMessage:
          "Bonjour Mayan Xperience Tours! Je suis intéressé par l'Expérience Isla Mujeres.",
      },
    },
  },
  {
    id: "cozumel",
    slug: "cozumel",
    legacyPath: "/cozumel",
    type: "experience",
    category: categoryIds.caribbeanIslands,
    status: "published",
    priority: "standard",
    assetBasePath: "/images/experiences/cozumel",
    cardImage: "/images/experiences/cozumel/card.jpg",
    cardImageAlt:
      "Snorkeler swimming above starfish in the turquoise waters of Cozumel.",
    cardImageObjectPosition: "center 58%",
    heroImage: "/images/experiences/cozumel/hero.jpg",
    heroAlt: "El Cielito turquoise water and boats in Cozumel.",
    gallery: [
      "/images/experiences/cozumel/card.jpg",
      "/images/experiences/cozumel/gallery/gallery-01.jpg",
      "/images/experiences/cozumel/gallery/gallery-02.jpg",
      "/images/experiences/cozumel/gallery/gallery-03.jpg",
      "/images/experiences/cozumel/gallery/gallery-04.jpg",
      "/images/experiences/cozumel/gallery/gallery-05.jpg",
      "/images/experiences/cozumel/gallery/gallery-06.jpg",
    ],
    relatedProductIds: ["isla-mujeres"],
    recommendedServiceIds: ["private-transportation", "photography", "drone-photography"],
    recommendedExperienceIds: ["isla-mujeres", "snorkeling-with-turtles-cenote"],
    tripBuilderEligible: true,
    seo: {
      title: "Cozumel Tours | Snorkeling, El Cielo & Caribbean Experiences",
      description:
        "Discover Cozumel with snorkeling in Colombia Reef, El Cielo, El Cielito, sea stars, Caribbean water and free time in downtown Cozumel.",
      openGraph: {
        title: "Cozumel Tours | Mayan Xperience Tours",
        description:
          "Discover Cozumel with snorkeling in Colombia Reef, El Cielo, El Cielito, sea stars, Caribbean water and free time in downtown Cozumel.",
        url: "/cozumel",
        images: [
          {
            url: "/images/experiences/cozumel/hero.jpg",
            width: 1200,
            height: 630,
            alt: "El Cielito turquoise water and boats in Cozumel",
          },
        ],
      },
      twitter: {
        card: "summary_large_image",
        title: "Cozumel Tours | Mayan Xperience Tours",
        description:
          "Discover Cozumel with snorkeling in Colombia Reef, El Cielo, El Cielito, sea stars, Caribbean water and free time in downtown Cozumel.",
        images: [
          {
            url: "/images/experiences/cozumel/hero.jpg",
            alt: "El Cielito turquoise water and boats in Cozumel",
          },
        ],
      },
    },
    content: {
      en: {
        title: "Cozumel",
        subtitle:
          "A premium Caribbean snorkeling escape with Colombia Reef, El Cielo, El Cielito, sea stars and crystal-clear water designed for travelers who love the ocean.",
        shortDescription:
          "Snorkel Colombia Reef, visit El Cielo and El Cielito, then enjoy free time in downtown Cozumel.",
        galleryTitle: "Experience Gallery",
        whatToExpectTitle: "What to Expect",
        whatToExpect:
          "Discover Cozumel through its most beautiful Caribbean scenes, from the colorful marine life of Colombia Reef to the shallow turquoise water of El Cielo and El Cielito. This experience is designed for snorkeling lovers who want a relaxed, high-quality day surrounded by crystal-clear water, soft sandbanks and the unforgettable sight of sea stars in their natural environment.\n\nYour day can also include a visit to the Turtle Sanctuary and free time in downtown Cozumel, where you can enjoy the island atmosphere before returning. Ferry transportation details are coordinated clearly so your crossing between Playa del Carmen and Cozumel feels simple, organized and stress-free.",
        highlightsTitle: "Highlights",
        highlights: [
          "Snorkeling in Colombia Reef",
          "Visit to El Cielo and El Cielito",
          "Sea stars in crystal-clear Caribbean water",
          "Turtle Sanctuary experience",
          "Free time in downtown Cozumel",
          "Small group experience",
        ],
        perfectForTitle: "Perfect For",
        perfectFor: [
          "Snorkeling Lovers",
          "Couples",
          "Families",
          "Small Groups",
          "Caribbean Water Enthusiasts",
        ],
        includedTitle: "What's Included",
        included: [
          "Cozumel snorkeling experience",
          "Colombia Reef, El Cielo and El Cielito route information",
          "Turtle Sanctuary visit information",
          "Free time guidance for downtown Cozumel",
          "Ferry transportation guidance",
          "Personalized assistance before booking",
        ],
        notIncludedTitle: "What's Not Included",
        notIncluded: [
          "Personal expenses",
          "Meals and drinks not confirmed in your selected package",
          "Tips",
          "Optional upgrades or private services",
        ],
        importantInformationTitle: "Important Information",
        importantInformation: [
          "Ferry transportation between Playa del Carmen and Cozumel is coordinated according to your selected schedule.",
          "Final inclusions may vary depending on the package and availability.",
          "Sea conditions may affect the snorkeling route for safety and comfort.",
          "This experience is ideal for guests who are comfortable in the water.",
        ],
        recommendationTitle: "Why We Recommend This Experience",
        recommendation:
          "Cozumel offers some of the clearest water in the Mexican Caribbean and one of the most memorable snorkeling settings in the region. It is the right choice for guests who want a beautiful island day focused on marine life, turquoise water and a relaxed small group experience.",
        ctaTitle: "Ready to Discover Cozumel?",
        ctaText:
          "Tell us your travel date and group size, and we will help you choose the best Cozumel experience.",
        whatsappButton: "Get Personalized Quote",
        whatsappMessage:
          "Hello Mayan Xperience Tours! I am interested in the Cozumel Experience.",
      },
      es: {
        title: "Cozumel",
        subtitle:
          "Una escapada premium de snorkel en el Caribe con Arrecife Colombia, El Cielo, El Cielito, estrellas de mar y aguas cristalinas para quienes aman el mar.",
        shortDescription:
          "Haz snorkel en el Arrecife Colombia, visita El Cielo y El Cielito, y disfruta tiempo libre en el centro de Cozumel.",
        galleryTitle: "Galería de la Experiencia",
        whatToExpectTitle: "Qué Puedes Esperar",
        whatToExpect:
          "Descubre Cozumel a través de sus paisajes caribeños más hermosos, desde la vida marina del Arrecife Colombia hasta las aguas turquesa y poco profundas de El Cielo y El Cielito. Esta experiencia está diseñada para amantes del snorkel que buscan un día relajado y de alta calidad entre aguas cristalinas, bancos de arena suave y la inolvidable vista de estrellas de mar en su entorno natural.\n\nTu día también puede incluir una visita al Santuario de Tortugas y tiempo libre en el centro de Cozumel, donde podrás disfrutar el ambiente de la isla antes de regresar. La información del ferry se coordina con claridad para que el cruce entre Playa del Carmen y Cozumel sea sencillo, organizado y sin estrés.",
        highlightsTitle: "Lo Más Destacado",
        highlights: [
          "Snorkel en el Arrecife Colombia",
          "Visita a El Cielo y El Cielito",
          "Estrellas de mar en aguas caribeñas cristalinas",
          "Experiencia en el Santuario de Tortugas",
          "Tiempo libre en el centro de Cozumel",
          "Experiencia en grupo pequeño",
        ],
        perfectForTitle: "Ideal Para",
        perfectFor: [
          "Amantes del Snorkel",
          "Parejas",
          "Familias",
          "Grupos Pequeños",
          "Amantes del Agua Caribeña",
        ],
        includedTitle: "Qué Incluye",
        included: [
          "Experiencia de snorkel en Cozumel",
          "Información de ruta por Arrecife Colombia, El Cielo y El Cielito",
          "Información de visita al Santuario de Tortugas",
          "Orientación para el tiempo libre en el centro de Cozumel",
          "Orientación sobre transporte en ferry",
          "Asistencia personalizada antes de reservar",
        ],
        notIncludedTitle: "Qué No Incluye",
        notIncluded: [
          "Gastos personales",
          "Alimentos y bebidas no confirmados en el paquete seleccionado",
          "Propinas",
          "Mejoras opcionales o servicios privados",
        ],
        importantInformationTitle: "Información Importante",
        importantInformation: [
          "El transporte en ferry entre Playa del Carmen y Cozumel se coordina de acuerdo con el horario seleccionado.",
          "Las inclusiones finales pueden variar según el paquete y la disponibilidad.",
          "Las condiciones del mar pueden modificar la ruta de snorkel por seguridad y comodidad.",
          "Esta experiencia es ideal para visitantes que se sienten cómodos en el agua.",
        ],
        recommendationTitle: "Por Qué Recomendamos Esta Experiencia",
        recommendation:
          "Cozumel ofrece algunas de las aguas más cristalinas del Caribe mexicano y uno de los escenarios de snorkel más memorables de la región. Es la opción ideal para quienes desean un día de isla enfocado en vida marina, agua turquesa y una experiencia relajada en grupo pequeño.",
        ctaTitle: "¿Listo para Descubrir Cozumel?",
        ctaText:
          "Cuéntanos tu fecha de viaje y el tamaño de tu grupo, y te ayudaremos a elegir la mejor experiencia en Cozumel.",
        whatsappButton: "Solicitar Cotización Personalizada",
        whatsappMessage:
          "Hola Mayan Xperience Tours! Estoy interesado en la Experiencia Cozumel.",
      },
      fr: {
        title: "Cozumel",
        subtitle:
          "Une escapade snorkeling premium dans les Caraïbes avec le récif Colombia, El Cielo, El Cielito, des étoiles de mer et une eau cristalline pour les amoureux de l'océan.",
        shortDescription:
          "Faites du snorkeling au récif Colombia, visitez El Cielo et El Cielito, puis profitez de temps libre dans le centre de Cozumel.",
        galleryTitle: "Galerie de l'Expérience",
        whatToExpectTitle: "À Quoi Vous Attendre",
        whatToExpect:
          "Découvrez Cozumel à travers ses plus beaux paysages caribéens, de la vie marine colorée du récif Colombia aux eaux turquoise peu profondes d'El Cielo et d'El Cielito. Cette expérience est pensée pour les passionnés de snorkeling qui recherchent une journée détendue et de grande qualité, entourés d'eau cristalline, de bancs de sable doux et de l'image inoubliable des étoiles de mer dans leur environnement naturel.\n\nVotre journée peut également inclure une visite au Sanctuaire des Tortues et du temps libre dans le centre de Cozumel, afin de profiter de l'ambiance de l'île avant le retour. Les informations concernant le ferry sont coordonnées clairement pour que la traversée entre Playa del Carmen et Cozumel soit simple, organisée et sans stress.",
        highlightsTitle: "Points Forts",
        highlights: [
          "Snorkeling au récif Colombia",
          "Visite d'El Cielo et d'El Cielito",
          "Étoiles de mer dans une eau caribéenne cristalline",
          "Expérience au Sanctuaire des Tortues",
          "Temps libre dans le centre de Cozumel",
          "Expérience en petit groupe",
        ],
        perfectForTitle: "Parfait Pour",
        perfectFor: [
          "Amoureux du Snorkeling",
          "Couples",
          "Familles",
          "Petits Groupes",
          "Passionnés d'Eaux Caribéennes",
        ],
        includedTitle: "Ce Qui Est Inclus",
        included: [
          "Expérience snorkeling à Cozumel",
          "Informations sur l'itinéraire récif Colombia, El Cielo et El Cielito",
          "Informations pour la visite du Sanctuaire des Tortues",
          "Conseils pour le temps libre dans le centre de Cozumel",
          "Conseils concernant le transport en ferry",
          "Assistance personnalisée avant la réservation",
        ],
        notIncludedTitle: "Ce Qui N'est Pas Inclus",
        notIncluded: [
          "Dépenses personnelles",
          "Repas et boissons non confirmés dans le forfait sélectionné",
          "Pourboires",
          "Options supplémentaires ou services privés",
        ],
        importantInformationTitle: "Informations Importantes",
        importantInformation: [
          "Le transport en ferry entre Playa del Carmen et Cozumel est coordonné selon l'horaire sélectionné.",
          "Les inclusions finales peuvent varier selon le forfait et la disponibilité.",
          "Les conditions de mer peuvent modifier l'itinéraire de snorkeling pour des raisons de sécurité et de confort.",
          "Cette expérience est idéale pour les voyageurs à l'aise dans l'eau.",
        ],
        recommendationTitle: "Pourquoi Nous Recommandons Cette Expérience",
        recommendation:
          "Cozumel offre certaines des eaux les plus claires des Caraïbes mexicaines et l'un des décors de snorkeling les plus mémorables de la région. C'est le bon choix pour les voyageurs qui souhaitent une belle journée insulaire axée sur la vie marine, l'eau turquoise et une expérience détendue en petit groupe.",
        ctaTitle: "Prêt à Découvrir Cozumel ?",
        ctaText:
          "Indiquez-nous votre date de voyage et la taille de votre groupe, et nous vous aiderons à choisir la meilleure expérience à Cozumel.",
        whatsappButton: "Obtenir un Devis Personnalisé",
        whatsappMessage:
          "Bonjour Mayan Xperience Tours! Je suis intéressé par l'Expérience Cozumel.",
      },
    },
  },
  {
    id: "isla-contoy",
    slug: "isla-contoy",
    legacyPath: "/isla-contoy",
    type: "experience",
    category: categoryIds.caribbeanIslands,
    status: "published",
    priority: "standard",
    assetBasePath: "/images/experiences/isla-contoy",
    cardImage: "/images/experiences/isla-contoy/catalog-aerial.png",
    cardImageAlt: "Aerial view of Isla Contoy surrounded by turquoise Caribbean water.",
    cardImageObjectPosition: "center 62%",
    heroImage: "/images/experiences/isla-contoy/playa-contoy.png",
    heroImageObjectPosition: "center 60%",
    heroAlt: "Aerial view of Isla Contoy surrounded by turquoise Caribbean water.",
    gallery: [
      "/images/experiences/isla-contoy/isla-de-arriba.png",
      "/images/experiences/isla-contoy/bote-contoy.png",
      "/images/experiences/isla-contoy/playa-contoy.png",
      "/images/experiences/isla-contoy/playa-contoy-2.png",
      "/images/experiences/isla-contoy/snorkel-contoy.png",
      "/images/experiences/isla-contoy/puente-contoy.png",
    ],
    relatedProductIds: ["isla-mujeres"],
    recommendedServiceIds: ["private-transportation", "photography", "drone-photography"],
    recommendedExperienceIds: ["isla-mujeres", "cozumel"],
    tripBuilderEligible: true,
    seo: {
      title: "Isla Contoy Tours | Nature, Snorkeling & Caribbean Beaches",
      description:
        "Discover Isla Contoy on a nature-focused Caribbean escape with snorkeling, white-sand beaches, turquoise water and protected wildlife.",
      openGraph: {
        title: "Isla Contoy Tours | Mayan Xperience Tours",
        description:
          "Visit protected Isla Contoy for snorkeling, pristine beaches, turquoise Caribbean water and remarkable wildlife.",
        url: "/isla-contoy",
        images: [{
          url: "/images/experiences/isla-contoy/isla-de-arriba.png",
          width: 1535,
          height: 1024,
          alt: "Aerial view of Isla Contoy surrounded by turquoise Caribbean water",
        }],
      },
      twitter: {
        card: "summary_large_image",
        title: "Isla Contoy Tours | Mayan Xperience Tours",
        description:
          "Visit protected Isla Contoy for snorkeling, pristine beaches, turquoise Caribbean water and remarkable wildlife.",
        images: [{
          url: "/images/experiences/isla-contoy/isla-de-arriba.png",
          alt: "Aerial view of Isla Contoy surrounded by turquoise Caribbean water",
        }],
      },
    },
    content: {
      en: {
        title: "Isla Contoy",
        subtitle: "A protected Caribbean island where pristine beaches, vibrant reefs and remarkable birdlife create an unforgettable nature escape.",
        shortDescription: "Sail to protected Isla Contoy for snorkeling, wildlife and time on a pristine white-sand beach.",
        galleryTitle: "Experience Gallery",
        whatToExpectTitle: "What to Expect",
        whatToExpect: "Travel across the Caribbean to Isla Contoy, a protected national park known for clear turquoise water, quiet white-sand beaches and extraordinary coastal wildlife. Your experience combines a scenic boat journey with guided time in an environment carefully preserved for nature.\n\nDepending on sea conditions and your selected package, the day may include snorkeling on a nearby reef, a guided island walk, beach time and a freshly prepared lunch. Visitor access is limited, giving Isla Contoy a peaceful character unlike the region's busier island destinations.",
        highlightsTitle: "Highlights",
        highlights: ["Protected national park island", "Snorkeling in clear Caribbean water", "White-sand beaches and turquoise shallows", "Birdwatching and guided nature discovery", "Scenic boat journey", "Limited-visitor natural setting"],
        perfectForTitle: "Perfect For",
        perfectFor: ["Nature Lovers", "Couples", "Families", "Snorkeling Enthusiasts", "Travelers Seeking a Peaceful Island Day"],
        includedTitle: "What's Included",
        included: ["Boat transportation to Isla Contoy", "Snorkeling equipment and guidance", "Guided island visit", "Food and refreshments according to your selected package", "Personalized assistance before booking"],
        notIncludedTitle: "What's Not Included",
        notIncluded: ["Personal expenses", "Tips", "Optional upgrades or private services", "Any conservation fee not confirmed in your selected package"],
        importantInformationTitle: "Important Information",
        importantInformation: ["Daily access is limited and advance booking is strongly recommended.", "The itinerary may change due to weather, sea conditions or park regulations.", "Wildlife sightings cannot be guaranteed.", "Biodegradable sun protection and respectful wildlife practices are essential."],
        recommendationTitle: "Why We Recommend This Experience",
        recommendation: "Isla Contoy is one of the Mexican Caribbean's most special day trips: quiet, beautiful and genuinely centered on nature. It is ideal for travelers who value conservation, uncrowded beaches and a slower island experience.",
        ctaTitle: "Ready to Discover Isla Contoy?",
        ctaText: "Tell us your travel date and group size, and we will help you select the best available Isla Contoy experience.",
        whatsappButton: "Get Personalized Quote",
        whatsappMessage: "Hello Mayan Xperience Tours! I am interested in the Isla Contoy Experience.",
      },
      es: {
        title: "Isla Contoy",
        subtitle: "Una isla protegida del Caribe donde playas vírgenes, arrecifes llenos de vida y aves extraordinarias crean una escapada inolvidable.",
        shortDescription: "Navega a la protegida Isla Contoy para disfrutar snorkel, vida silvestre y una playa virgen de arena blanca.",
        galleryTitle: "Galería de la Experiencia",
        whatToExpectTitle: "Qué Puedes Esperar",
        whatToExpect: "Cruza el Caribe hacia Isla Contoy, un parque nacional protegido conocido por sus aguas turquesa, tranquilas playas de arena blanca y extraordinaria vida costera. La experiencia combina un paseo panorámico en barco con tiempo guiado en un entorno cuidadosamente conservado.\n\nSegún las condiciones del mar y el paquete seleccionado, el día puede incluir snorkel en un arrecife cercano, una caminata guiada por la isla, tiempo de playa y comida recién preparada. El acceso limitado mantiene la atmósfera tranquila que distingue a Isla Contoy de otros destinos insulares de la región.",
        highlightsTitle: "Lo Más Destacado",
        highlights: ["Isla protegida como parque nacional", "Snorkel en aguas cristalinas del Caribe", "Playas blancas y aguas turquesa", "Observación de aves y recorrido natural guiado", "Paseo panorámico en barco", "Entorno natural con acceso limitado"],
        perfectForTitle: "Ideal Para",
        perfectFor: ["Amantes de la Naturaleza", "Parejas", "Familias", "Amantes del Snorkel", "Viajeros que Buscan un Día de Isla Tranquilo"],
        includedTitle: "Qué Incluye",
        included: ["Transporte en barco a Isla Contoy", "Equipo y orientación de snorkel", "Visita guiada por la isla", "Alimentos y bebidas según el paquete seleccionado", "Asistencia personalizada antes de reservar"],
        notIncludedTitle: "Qué No Incluye",
        notIncluded: ["Gastos personales", "Propinas", "Mejoras opcionales o servicios privados", "Cuota de conservación no confirmada en el paquete seleccionado"],
        importantInformationTitle: "Información Importante",
        importantInformation: ["El acceso diario es limitado y se recomienda reservar con anticipación.", "El itinerario puede cambiar por clima, condiciones del mar o reglas del parque.", "No se pueden garantizar avistamientos de fauna.", "Es esencial usar protección solar biodegradable y respetar la vida silvestre."],
        recommendationTitle: "Por Qué Recomendamos Esta Experiencia",
        recommendation: "Isla Contoy es una de las excursiones más especiales del Caribe mexicano: tranquila, hermosa y verdaderamente enfocada en la naturaleza. Es ideal para quienes valoran la conservación, las playas sin multitudes y una experiencia isleña más relajada.",
        ctaTitle: "¿Listo para Descubrir Isla Contoy?",
        ctaText: "Cuéntanos tu fecha de viaje y el tamaño de tu grupo, y te ayudaremos a elegir la mejor experiencia disponible en Isla Contoy.",
        whatsappButton: "Solicitar Cotización Personalizada",
        whatsappMessage: "Hola Mayan Xperience Tours! Estoy interesado en la Experiencia Isla Contoy.",
      },
      fr: {
        title: "Isla Contoy",
        subtitle: "Une île protégée des Caraïbes où plages préservées, récifs vivants et oiseaux remarquables composent une escapade nature inoubliable.",
        shortDescription: "Naviguez vers Isla Contoy pour faire du snorkeling, observer la faune et profiter d'une plage de sable blanc préservée.",
        galleryTitle: "Galerie de l'Expérience",
        whatToExpectTitle: "À Quoi Vous Attendre",
        whatToExpect: "Traversez les Caraïbes jusqu'à Isla Contoy, un parc national protégé réputé pour ses eaux turquoise, ses plages tranquilles de sable blanc et sa remarquable faune côtière. L'expérience associe une traversée panoramique en bateau à une découverte guidée d'un environnement soigneusement préservé.\n\nSelon les conditions maritimes et le forfait choisi, la journée peut inclure du snorkeling près d'un récif, une promenade guidée sur l'île, du temps à la plage et un déjeuner fraîchement préparé. L'accès limité confère à Isla Contoy une atmosphère paisible, différente des îles plus fréquentées de la région.",
        highlightsTitle: "Points Forts",
        highlights: ["Île protégée classée parc national", "Snorkeling dans une eau caribéenne cristalline", "Plages blanches et lagons turquoise", "Observation des oiseaux et découverte guidée", "Traversée panoramique en bateau", "Site naturel à accès limité"],
        perfectForTitle: "Parfait Pour",
        perfectFor: ["Amoureux de la Nature", "Couples", "Familles", "Passionnés de Snorkeling", "Voyageurs en Quête d'une Journée Paisible"],
        includedTitle: "Ce Qui Est Inclus",
        included: ["Transport en bateau vers Isla Contoy", "Équipement et encadrement de snorkeling", "Visite guidée de l'île", "Repas et rafraîchissements selon le forfait choisi", "Assistance personnalisée avant la réservation"],
        notIncludedTitle: "Ce Qui N'est Pas Inclus",
        notIncluded: ["Dépenses personnelles", "Pourboires", "Options supplémentaires ou services privés", "Frais de conservation non confirmés dans le forfait choisi"],
        importantInformationTitle: "Informations Importantes",
        importantInformation: ["L'accès quotidien est limité; il est fortement conseillé de réserver à l'avance.", "L'itinéraire peut changer selon la météo, l'état de la mer ou les règles du parc.", "Les observations d'animaux sauvages ne peuvent pas être garanties.", "Une protection solaire biodégradable et le respect de la faune sont essentiels."],
        recommendationTitle: "Pourquoi Nous Recommandons Cette Expérience",
        recommendation: "Isla Contoy est l'une des excursions les plus exceptionnelles des Caraïbes mexicaines : paisible, magnifique et véritablement tournée vers la nature. Elle convient aux voyageurs sensibles à la conservation et aux plages peu fréquentées.",
        ctaTitle: "Prêt à Découvrir Isla Contoy ?",
        ctaText: "Indiquez-nous votre date de voyage et la taille de votre groupe, et nous vous aiderons à choisir la meilleure expérience disponible à Isla Contoy.",
        whatsappButton: "Obtenir un Devis Personnalisé",
        whatsappMessage: "Bonjour Mayan Xperience Tours! Je suis intéressé par l'Expérience Isla Contoy.",
      },
    },
  },
  {
    id: "holbox",
    slug: "holbox",
    legacyPath: "/holbox",
    type: "experience",
    category: categoryIds.caribbeanIslands,
    status: "published",
    priority: "standard",
    cardImage: "/images/experiences/holbox/muro-playa.png",
    cardImageAlt: "Colorful Holbox beach mural beside the Caribbean Sea.",
    heroImage: "/images/experiences/holbox/salto-playa.jpg",
    heroAlt: "Caribbean scenery in Holbox, Mexico.",
    gallery: [
      "/images/experiences/holbox/muro-playa.png",
      "/images/experiences/holbox/salto-playa.jpg",
      "/images/experiences/holbox/estrella-de-mar.png",
      "/images/experiences/holbox/mural.png",
      "/images/experiences/holbox/concha-playa.png",
      "/images/experiences/holbox/columpios.png",
      "/images/experiences/holbox/mural-2.png",
      "/images/experiences/holbox/espejo.png",
      "/images/experiences/holbox/pagina-principal.png",
      "/images/experiences/holbox/mural-3.png",
      "/images/experiences/holbox/nido.jpg",
      "/images/experiences/holbox/mural-4.jpeg",
      "/images/experiences/holbox/escaleras.png",
      "/images/experiences/holbox/hero-riviera-maya.jpg",
    ],
    relatedProductIds: [],
    recommendedServiceIds: [],
    recommendedExperienceIds: [],
    tripBuilderEligible: true,
    seo: {
      title: "Holbox Tours | Beaches, Wildlife & Island Experiences",
      description:
        "Discover Holbox with white-sand beaches, shallow turquoise water, colorful murals, wildlife, golf cart adventures and a relaxed Caribbean atmosphere.",
      openGraph: {
        title: "Holbox Tours | Mayan Xperience Tours",
        description:
          "Escape to Holbox for beautiful beaches, colorful streets, wildlife and an unforgettable laid-back island experience.",
        url: "/holbox",
        images: [{
          url: "/images/experiences/holbox/salto-playa.jpg",
          width: 1200,
          height: 630,
          alt: "White-sand beach and shallow Caribbean water in Holbox",
        }],
      },
      twitter: {
        card: "summary_large_image",
        title: "Holbox Tours | Mayan Xperience Tours",
        description:
          "Escape to Holbox for beautiful beaches, colorful streets, wildlife and an unforgettable laid-back island experience.",
        images: [{
          url: "/images/experiences/holbox/salto-playa.jpg",
          alt: "White-sand beach and shallow Caribbean water in Holbox",
        }],
      },
    },
    content: {
      en: {
        title: "Holbox",
        subtitle:
          "🏝️ Escape to Holbox, one of Mexico's most breathtaking island paradises. Famous for its white-sand beaches, crystal-clear shallow waters, colorful street art, vibrant wildlife, and laid-back atmosphere, Holbox offers the perfect combination of relaxation and adventure. Whether you're exploring hidden beaches, discovering natural wonders, or simply enjoying the peaceful island lifestyle, Holbox is an unforgettable Caribbean experience.",
        shortDescription:
          "Discover white-sand beaches, colorful streets, wildlife and the easygoing Caribbean spirit of Holbox.",
        longDescription:
          "A relaxed island escape that brings together nature, local culture and some of the most beautiful coastal scenery in the Mexican Caribbean.",
        galleryTitle: "Explore the Beauty of Holbox",
        whatToExpectTitle: "What to Expect 🌴",
        whatToExpect:
          "Your Holbox experience unfolds at an easy island pace. Enjoy time beside calm, shallow Caribbean water, walk along white-sand beaches and discover streets filled with colorful murals, welcoming restaurants and the unmistakable character of local island life. Scenic viewpoints and natural landscapes offer memorable stops throughout the day.\n\n🚤 Depending on your selected experience, you may explore by golf cart, visit the island's best-known attractions or simply enjoy free time to swim, take photographs, taste local food and relax. Holbox is less about rushing from one stop to another and more about enjoying the freedom, beauty and peaceful rhythm of the Caribbean.",
        highlightsTitle: "Highlights ✨",
        highlights: [
          "White-sand beaches",
          "Crystal-clear shallow waters",
          "Colorful murals and lively island streets",
          "Scenic coastal viewpoints",
          "Relaxed Caribbean atmosphere",
          "Local restaurants and island flavors",
          "Golf cart exploration",
          "Wildlife and natural surroundings",
        ],
        experienceStylesTitle: "Experience Style",
        experienceStyles: [
          "Relaxed",
          "Scenic",
          "Nature",
          "Photography",
          "Beach Escape",
          "Local Culture",
        ],
        perfectForTitle: "Perfect For 📸",
        perfectFor: [
          "Couples",
          "Families",
          "Groups of Friends",
          "Nature Lovers",
          "Beach Lovers",
          "Photographers",
          "Travelers Looking to Relax",
        ],
        includedTitle: "What's Included 🚤",
        included: [
          "Round-trip transportation according to your selected package",
          "Ferry transportation when included in the selected tour",
          "Guided assistance throughout the experience",
          "Free time in Holbox",
          "Visit to the main attractions included in your itinerary",
          "Public beach access",
          "Personalized assistance before booking",
        ],
        notIncludedTitle: "What's Not Included",
        notIncluded: [
          "Personal expenses",
          "Meals and drinks not confirmed in your selected package",
          "Optional activities or rentals",
          "Souvenirs",
          "Tips",
        ],
        importantInformationTitle: "What to Bring ☀️",
        importantInformation: [
          "Swimsuit and towel",
          "Sunglasses and a hat",
          "Comfortable sandals or walking shoes",
          "Biodegradable sunscreen",
          "Camera or phone for photographs",
          "Cash for small purchases and optional tips",
        ],
        recommendationTitle: "Why We Recommend This Experience 🌊",
        recommendation:
          "Holbox offers a refreshing contrast to busier Caribbean destinations. Its shallow turquoise water, artistic streets, natural beauty and unhurried lifestyle make it a wonderful choice for travelers who want a beach day with genuine island character, freedom to explore and plenty of memorable photo opportunities.",
        ctaTitle: "Ready to Discover Holbox?",
        ctaText:
          "Tell us your travel date and group size, and we will help you choose the Holbox experience that best fits your plans.",
        whatsappButton: "Get Personalized Quote",
        whatsappMessage:
          "Hello Mayan Xperience Tours! I am interested in the Holbox Experience.",
      },
      es: {
        title: "Holbox",
        subtitle:
          "🏝️ Escápate a Holbox, uno de los paraísos insulares más impresionantes de México. Famosa por sus playas de arena blanca, aguas cristalinas y poco profundas, arte urbano colorido, abundante vida silvestre y ambiente relajado, Holbox ofrece la combinación perfecta de descanso y aventura. Ya sea que explores playas escondidas, descubras maravillas naturales o simplemente disfrutes el tranquilo estilo de vida isleño, Holbox es una experiencia caribeña inolvidable.",
        shortDescription:
          "Descubre playas de arena blanca, calles coloridas, vida silvestre y el espíritu caribeño de Holbox.",
        longDescription:
          "Una escapada isleña relajada que reúne naturaleza, cultura local y algunos de los paisajes costeros más hermosos del Caribe mexicano.",
        galleryTitle: "Explora la Belleza de Holbox",
        whatToExpectTitle: "Qué Puedes Esperar 🌴",
        whatToExpect:
          "Tu experiencia en Holbox transcurre al tranquilo ritmo de la isla. Disfruta tiempo junto a aguas caribeñas calmadas y poco profundas, camina por playas de arena blanca y descubre calles llenas de murales, restaurantes acogedores y el carácter único de la vida local. Los miradores y paisajes naturales ofrecen paradas memorables durante el día.\n\n🚤 Según la experiencia seleccionada, podrás explorar en carrito de golf, visitar las atracciones más conocidas o disfrutar tiempo libre para nadar, tomar fotografías, probar la gastronomía local y relajarte. Holbox no se trata de correr de una parada a otra, sino de disfrutar la libertad, la belleza y el ritmo sereno del Caribe.",
        highlightsTitle: "Lo Más Destacado ✨",
        highlights: [
          "Playas de arena blanca",
          "Aguas cristalinas y poco profundas",
          "Murales coloridos y calles llenas de vida",
          "Miradores costeros",
          "Ambiente caribeño relajado",
          "Restaurantes locales y sabores de la isla",
          "Exploración en carrito de golf",
          "Vida silvestre y entornos naturales",
        ],
        experienceStylesTitle: "Estilo de la Experiencia",
        experienceStyles: [
          "Relajada",
          "Panorámica",
          "Naturaleza",
          "Fotografía",
          "Escapada de Playa",
          "Cultura Local",
        ],
        perfectForTitle: "Ideal Para 📸",
        perfectFor: [
          "Parejas",
          "Familias",
          "Grupos de Amigos",
          "Amantes de la Naturaleza",
          "Amantes de la Playa",
          "Fotógrafos",
          "Viajeros que Buscan Relajarse",
        ],
        includedTitle: "Qué Incluye 🚤",
        included: [
          "Transporte redondo según el paquete seleccionado",
          "Transporte en ferry cuando esté incluido en el tour seleccionado",
          "Asistencia guiada durante la experiencia",
          "Tiempo libre en Holbox",
          "Visita a las principales atracciones incluidas en el itinerario",
          "Acceso a playas públicas",
          "Asistencia personalizada antes de reservar",
        ],
        notIncludedTitle: "Qué No Incluye",
        notIncluded: [
          "Gastos personales",
          "Alimentos y bebidas no confirmados en el paquete seleccionado",
          "Actividades o rentas opcionales",
          "Souvenirs",
          "Propinas",
        ],
        importantInformationTitle: "Qué Llevar ☀️",
        importantInformation: [
          "Traje de baño y toalla",
          "Lentes de sol y sombrero",
          "Sandalias cómodas o calzado para caminar",
          "Protector solar biodegradable",
          "Cámara o teléfono para fotografías",
          "Efectivo para compras pequeñas y propinas opcionales",
        ],
        recommendationTitle: "Por Qué Recomendamos Esta Experiencia 🌊",
        recommendation:
          "Holbox ofrece un contraste refrescante con otros destinos caribeños más concurridos. Sus aguas turquesa poco profundas, calles artísticas, belleza natural y estilo de vida tranquilo la convierten en una opción maravillosa para quienes desean un día de playa con auténtico carácter isleño, libertad para explorar y muchas oportunidades para tomar fotografías inolvidables.",
        ctaTitle: "¿Listo para Descubrir Holbox?",
        ctaText:
          "Cuéntanos tu fecha de viaje y el tamaño de tu grupo, y te ayudaremos a elegir la experiencia en Holbox que mejor se adapte a tus planes.",
        whatsappButton: "Solicitar Cotización Personalizada",
        whatsappMessage:
          "Hola Mayan Xperience Tours! Estoy interesado en la Experiencia Holbox.",
      },
      fr: {
        title: "Holbox",
        subtitle:
          "🏝️ Évadez-vous à Holbox, l'un des plus beaux paradis insulaires du Mexique. Célèbre pour ses plages de sable blanc, ses eaux cristallines peu profondes, son art urbain coloré, sa faune variée et son ambiance décontractée, Holbox offre un équilibre parfait entre détente et aventure. Entre plages cachées, merveilles naturelles et douceur de vivre insulaire, Holbox promet une expérience caribéenne inoubliable.",
        shortDescription:
          "Découvrez les plages blanches, les rues colorées, la faune et l'esprit caribéen décontracté de Holbox.",
        longDescription:
          "Une escapade insulaire paisible qui réunit nature, culture locale et quelques-uns des plus beaux paysages côtiers des Caraïbes mexicaines.",
        galleryTitle: "Explorez la Beauté de Holbox",
        whatToExpectTitle: "À Quoi Vous Attendre 🌴",
        whatToExpect:
          "Votre expérience à Holbox se déroule au rythme paisible de l'île. Profitez des eaux calmes et peu profondes des Caraïbes, promenez-vous sur les plages de sable blanc et découvrez des rues animées par des fresques colorées, des restaurants accueillants et l'authenticité de la vie locale. Les points de vue et paysages naturels offrent des étapes mémorables tout au long de la journée.\n\n🚤 Selon l'expérience choisie, vous pourrez explorer l'île en voiturette de golf, visiter ses attractions emblématiques ou profiter de temps libre pour nager, prendre des photos, goûter la cuisine locale et vous détendre. Holbox invite moins à courir d'une étape à l'autre qu'à savourer la liberté, la beauté et le rythme tranquille des Caraïbes.",
        highlightsTitle: "Points Forts ✨",
        highlights: [
          "Plages de sable blanc",
          "Eaux cristallines peu profondes",
          "Fresques colorées et rues pleines de vie",
          "Points de vue sur la côte",
          "Ambiance caribéenne détendue",
          "Restaurants locaux et saveurs de l'île",
          "Exploration en voiturette de golf",
          "Faune et paysages naturels",
        ],
        experienceStylesTitle: "Style de l'Expérience",
        experienceStyles: [
          "Détente",
          "Paysages",
          "Nature",
          "Photographie",
          "Escapade à la Plage",
          "Culture Locale",
        ],
        perfectForTitle: "Parfait Pour 📸",
        perfectFor: [
          "Couples",
          "Familles",
          "Groupes d'Amis",
          "Amoureux de la Nature",
          "Amoureux de la Plage",
          "Photographes",
          "Voyageurs en Quête de Détente",
        ],
        includedTitle: "Ce Qui Est Inclus 🚤",
        included: [
          "Transport aller-retour selon le forfait choisi",
          "Transport en ferry lorsqu'il est inclus dans l'excursion choisie",
          "Accompagnement pendant l'expérience",
          "Temps libre à Holbox",
          "Visite des principales attractions prévues dans l'itinéraire",
          "Accès aux plages publiques",
          "Assistance personnalisée avant la réservation",
        ],
        notIncludedTitle: "Ce Qui N'est Pas Inclus",
        notIncluded: [
          "Dépenses personnelles",
          "Repas et boissons non confirmés dans le forfait choisi",
          "Activités ou locations facultatives",
          "Souvenirs",
          "Pourboires",
        ],
        importantInformationTitle: "À Apporter ☀️",
        importantInformation: [
          "Maillot de bain et serviette",
          "Lunettes de soleil et chapeau",
          "Sandales confortables ou chaussures de marche",
          "Crème solaire biodégradable",
          "Appareil photo ou téléphone",
          "Espèces pour les petits achats et les pourboires facultatifs",
        ],
        recommendationTitle: "Pourquoi Nous Recommandons Cette Expérience 🌊",
        recommendation:
          "Holbox offre une alternative rafraîchissante aux destinations caribéennes plus fréquentées. Ses eaux turquoise peu profondes, ses rues artistiques, sa beauté naturelle et son rythme tranquille en font un excellent choix pour les voyageurs qui souhaitent une journée à la plage avec une véritable identité insulaire, la liberté d'explorer et de nombreuses occasions de prendre des photos mémorables.",
        ctaTitle: "Prêt à Découvrir Holbox ?",
        ctaText:
          "Indiquez-nous votre date de voyage et la taille de votre groupe, et nous vous aiderons à choisir l'expérience à Holbox qui correspond le mieux à vos projets.",
        whatsappButton: "Obtenir un Devis Personnalisé",
        whatsappMessage:
          "Bonjour Mayan Xperience Tours! Je suis intéressé par l'Expérience Holbox.",
      },
    },
  },
  {
    id: "sunset-catamaran",
    slug: "sunset-catamaran",
    type: "experience",
    category: categoryIds.caribbeanIslands,
    status: "draft",
    priority: "standard",
    heroImage: "",
    heroAlt: "TODO: Add Sunset Catamaran hero image alt text.",
    gallery: [],
    relatedProductIds: ["isla-mujeres"],
    recommendedServiceIds: ["photography", "drone-photography"],
    recommendedExperienceIds: ["isla-mujeres"],
    tripBuilderEligible: true,
    seo: createTodoSeo("Sunset Catamaran"),
    content: createTodoContent("Sunset Catamaran"),
  },
] as const satisfies Array<ExperienceProduct & { category: ProductCategoryId }>;
