import { categoryIds, type ProductCategoryId } from "@/content/categories";
import { createTodoContent, createTodoSeo } from "@/content/products/shared";
import type { ExperienceProduct } from "@/types/product";

export const themeParkExperiences = [
  {
    id: "xcaret",
    slug: "xcaret",
    type: "experience",
    category: categoryIds.themeParks,
    status: "draft",
    priority: "standard",
    heroImage: "",
    heroAlt: "TODO: Add Xcaret hero image alt text.",
    gallery: [],
    relatedProductIds: [],
    recommendedServiceIds: [],
    recommendedExperienceIds: [],
    tripBuilderEligible: true,
    seo: createTodoSeo("Xcaret"),
    content: createTodoContent("Xcaret"),
  },
  {
    id: "xel-ha",
    slug: "xel-ha",
    type: "experience",
    category: categoryIds.themeParks,
    status: "draft",
    priority: "standard",
    heroImage: "",
    heroAlt: "TODO: Add Xel-Ha hero image alt text.",
    gallery: [],
    relatedProductIds: [],
    recommendedServiceIds: [],
    recommendedExperienceIds: [],
    tripBuilderEligible: true,
    seo: createTodoSeo("Xel-Ha"),
    content: createTodoContent({ en: "Xel-Ha", es: "Xel-Há", fr: "Xel-Há" }),
  },
  {
    id: "xplor",
    slug: "xplor",
    type: "experience",
    category: categoryIds.themeParks,
    status: "draft",
    priority: "standard",
    heroImage: "",
    heroAlt: "TODO: Add Xplor hero image alt text.",
    gallery: [],
    relatedProductIds: [],
    recommendedServiceIds: [],
    recommendedExperienceIds: [],
    tripBuilderEligible: true,
    seo: createTodoSeo("Xplor"),
    content: createTodoContent("Xplor"),
  },
  {
    id: "xenses",
    slug: "xenses",
    type: "experience",
    category: categoryIds.themeParks,
    status: "draft",
    priority: "standard",
    heroImage: "",
    heroAlt: "TODO: Add Xenses hero image alt text.",
    gallery: [],
    relatedProductIds: [],
    recommendedServiceIds: [],
    recommendedExperienceIds: [],
    tripBuilderEligible: true,
    seo: createTodoSeo("Xenses"),
    content: createTodoContent("Xenses"),
  },
  {
    id: "xenotes",
    slug: "xenotes",
    type: "experience",
    category: categoryIds.themeParks,
    status: "draft",
    priority: "standard",
    heroImage: "",
    heroAlt: "TODO: Add Xenotes hero image alt text.",
    gallery: [],
    relatedProductIds: ["cenotes"],
    recommendedServiceIds: [],
    recommendedExperienceIds: ["cenotes"],
    tripBuilderEligible: true,
    seo: createTodoSeo("Xenotes"),
    content: createTodoContent("Xenotes"),
  },
  {
    id: "xavage",
    slug: "xavage",
    type: "experience",
    category: categoryIds.themeParks,
    status: "draft",
    priority: "standard",
    heroImage: "",
    heroAlt: "TODO: Add Xavage hero image alt text.",
    gallery: [],
    relatedProductIds: [],
    recommendedServiceIds: [],
    recommendedExperienceIds: [],
    tripBuilderEligible: true,
    seo: createTodoSeo("Xavage"),
    content: createTodoContent("Xavage"),
  },
  {
    id: "xoximilco",
    slug: "xoximilco",
    type: "experience",
    category: categoryIds.themeParks,
    status: "draft",
    priority: "standard",
    heroImage: "",
    heroAlt: "TODO: Add Xoximilco hero image alt text.",
    gallery: [],
    relatedProductIds: [],
    recommendedServiceIds: [],
    recommendedExperienceIds: [],
    tripBuilderEligible: true,
    seo: createTodoSeo("Xoximilco"),
    content: createTodoContent("Xoximilco"),
  },
] as const satisfies Array<ExperienceProduct & { category: ProductCategoryId }>;
